### PR TITLE
Added support for individually named bower config files

### PR DESCRIPTION
**Pull request by therufa**
I added these changes to the code, because I have recently added a git repo to my bower config which was pulled correctly, but since its not registered on bower.io and has no "proper" bower config file (even though its there, but named different than its supposed to be) the library does not find it. 
Please review the changes. I'm interested in your opinion.

Now tested -.-

Thanks!

### CODE REVIEW

**Comment by ck86** [comment]
@therufa what git repo's do you added?

**Comment by therufa** [comment]
@ck86 Its an older private project maintained kept on local git, so there's a reason for it to be there. i know; why don't I change the the file name? I don't have write permission and i wont get it anytime soon. So i felt it was easier to change it here, with the hope that it eventually would benefit the community.

**Comment by ck86** [comment]
I get your point, but I think this issue is rarely, so isn't it easier to add those files manually?

**Comment by therufa** [comment]
@ck86 it actually isn't harder, its just a few more lines of code but still. Not very elegant if you understand what i mean. If you see no point in merging it into the master, i would simply maintain it under my fork, since its pretty useful to me.

**Comment by ck86** [comment]
It's just I don't want to blow up the functionality.

**Comment by therufa** [comment]
i get your point. i guess it should be closed then. Thanks anyways

**Comment by ck86** [comment]
Thank you anyway. ;)

**Pull request closed without merging**
