### PR TITLE
Enable dot option of multimatch(minimatch)

### PR DESCRIPTION
**Pull request by kaishuu0123**
## if working directory
* /var/foo/.bar/baz.scss

## before
```
mainBowerFiles({
      filter:'**/*.scss'
})
```

## after (this PR)
```
mainBowerFiles({
      filter:'**/*.scss'
})
```

### result
* match

### CODE REVIEW

**Comment by TrySound** [comment]
@kaishuu0123 Use case?

**Comment by kaishuu0123** [comment]
@TrySound  Thank you for your comments.
I want to build without thinking it or hidden directory or not.

**Comment by kaishuu0123** [comment]
@TrySound Thank you for your merge!
But not affect the other?

**Comment by TrySound** [comment]
@kaishuu0123 Tests are passed. So, hope not.)

**Comment by kaishuu0123** [comment]
@TrySound  I also tried to run the test  :) (make test-unit)
Thank you.

**Pull request merged**
