### PR TITLE
Feature/cli tool build with npm

### PR DESCRIPTION
**Pull request by saviogl**
Wrapping the main-bower-files into a CLI tool to allow the use of npm as an alternative build tool

### CODE REVIEW

**Comment by ck86** [comment]
Hey @saviogl thanks for your request, I don't know if this is really needed, but before I merge it please check your tests (https://travis-ci.org/ck86/main-bower-files/builds/116126881)

**Comment by TrySound** [comment]
@ck86 I think copying is not the only think which can be done with main-bower-files. But this is available only with other tools. So having own cli is not necessary stuff.

**Comment by ck86** [comment]
I agree to @TrySound. My suggestion is to create your own "npm build tool" which uses main-bower-files and we could leave a link in the readme.

**Comment by saviogl** [comment]
@ck86 Ok then. The idea was just hopping into the movement in which npm is used as a build tool, which I'm personally keen of. I'll take some time to create an own package on top of main-bower-files to make it available and let you guys know.

**Pull request closed without merging**
