### PR TITLE
Added a link to gulp-main-bower-files

### PR DESCRIPTION
**Pull request by mauricedb**

### CODE REVIEW

**Comment by TrySound** [comment]
@mauricedb https://github.com/deepak1556/gulp-browserify

**Comment by mauricedb** [comment]
@ck86, Not sure I understand the significance of the link above.

**Comment by TrySound** [comment]
@mauricedb There is no reason to use this simple wrapper, cause main-bower-files works fine out if the box.

**Comment by mauricedb** [comment]
@ck86, Just trying to make life a little easier. Thanks for the work you
did.

**Comment by ck86** [comment]
@mauricedb you are talking with @TrySound, but I have the same opinion. There is no reason to use a wrapper.

**Pull request closed without merging**
