### PR TITLE
Sort Queue by Dependency

### PR DESCRIPTION
**Pull request by keesey**
I've had a problem with files of dependencies appearing later in the list than the files that require them. Doing a sort on the queue seems to fix the problem.

### CODE REVIEW

**Comment by ck86** [comment]
hey @keesey
the packages should already be sorted, what is the problem?

**Comment by keesey** [comment]
That's what I thought looking at the code, but it wasn't working for two projects of mine. My change seems to have fixed it for one, but not the other, so this pull request is not a proper solution.

I'm going to get a few more details and then report it as an issue. It looks like the dependencies aren't being read correctly in some circumstances.

**Comment by ck86** [comment]
Can you share the bower.json? So I can have a look, too.

**Comment by keesey** [comment]
I figured it out! It's my fault.

I was overriding dependencies with an array, e.g, `"dependencies": ["jquery"]`. I should override them with an object, e.g., `"dependencies": {"jquery": "~2.1.3"}`. This is why I was getting weird stuff like a package called `"0"` that was a dependency for everything.

You might want to add a check to make it fail if someone tries to do that, but, yeah ... user error.

**Pull request closed without merging**
