### PR TITLE
add dependency group option

### PR DESCRIPTION
**Pull request by ball6847**
It would be great if we can define a group which contains only some packages from `dependencies` in `bower.json` file

Consider this bower.json file.

```json
{
  "dependencies": {
    "jquery": "~2.1.4",
    "angular": "1.4",
    "angular-ui-router": "~0.2.15",
    "restangular": "~1.5.1"
  },
  "group": {
    "home": [ "jquery" ],
    "admin": [ "jquery", "angular", "angular-ui-router" ]
  }
}
```

Notice the `group` section. In some cases just `jquery` is enough for the `home` page , and we may need more (or all of them) for other pages. Instead of creating separated bower.json file for each pages, defining a group section in bower.json would be easier to manage dependencies for the project (and the bower.json file itself)

Then we specify a group as an option for `mainBowerFile` like this.

```javascript
var mainBowerFiles = require('main-bower-files');

var files = mainBowerFiles({ paths: './' });
var homeFiles = mainBowerFiles({ paths: './', group: 'home' });

console.log(files);
// [ '/home/user/project/bower_components/jquery/dist/jquery.js',
//   '/home/user/project/bower_components/angular/angular.js',
//   '/home/user/project/bower_components/angular-ui-router/release/angular-ui-router.js',
//  ' /home/user/project/bower_components/lodash/lodash.js',
//   '/home/user/project/bower_components/restangular/dist/restangular.js' ]

console.log(homeFiles);
// [ '/home/user/project/bower_components/jquery/dist/jquery.js' ]

```

Hope this help,
Porawit Poboonma

### CODE REVIEW

**Comment by ck86** [comment]
Hey @ball6847 

thanks for that pull request.

There is an issue if you add a dependency to the group which does not exist. Can you fix this (including a test) and I will merge it!

**Comment by ck86** [comment]
And would you update the docs, too?

**Comment by ball6847** [comment]
@ck86 ok, more tests and docs added.

**Comment by ball6847** [comment]
Thank you for pointing out my mistakes. Fixed.

**Pull request merged**
